version: '3.7'
services:
  tempo-db:
    hostname: "tempo-db"
    restart: "no"
    image:  postgres:11
    ports:
      - "5432:5432"
    volumes:
      - "tempo_vols_db_data:/var/lib/postgresql/data"
      - "tempo_vols_db_logs:/var/log/postgresql"
    environment:
      - DEBUG=false
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tempo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  tempo:
    restart: "no"
    image: tempo:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tempo-db:5432/tempo
    depends_on:
      - tempo-db


volumes:
  tempo_vols_db_data:
  tempo_vols_db_logs:
